services:
  - type: web
    name: stock-screener-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r backend/requirements-prod.txt
    startCommand: cd backend && gunicorn app_demo:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
